# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/BaiduNetdiskDownload/fft_test3/fft_test3/fft_test3.srcs/sources_1/ip/xfft_f/xfft_f.xci
# IP: The module: 'xfft_f' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/BaiduNetdiskDownload/fft_test3/fft_test3/fft_test3.srcs/sources_1/ip/xfft_f/xfft_f_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_f'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/BaiduNetdiskDownload/fft_test3/fft_test3/fft_test3.srcs/sources_1/ip/xfft_f/xfft_f.xci
# IP: The module: 'xfft_f' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/BaiduNetdiskDownload/fft_test3/fft_test3/fft_test3.srcs/sources_1/ip/xfft_f/xfft_f_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_f'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
