# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/dell/Desktop/CameraLink/fft_test2/fft_test2.srcs/sources_1/ip/dds_compiler_1/dds_compiler_1.xci
# IP: The module: 'dds_compiler_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/CameraLink/fft_test2/fft_test2.srcs/sources_1/ip/dds_compiler_1/dds_compiler_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_compiler_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/dell/Desktop/CameraLink/fft_test2/fft_test2.srcs/sources_1/ip/dds_compiler_1/dds_compiler_1.xci
# IP: The module: 'dds_compiler_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/CameraLink/fft_test2/fft_test2.srcs/sources_1/ip/dds_compiler_1/dds_compiler_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_compiler_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
