@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sat Apr 22 11:11:54 +0800 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 46b40167271d49a78bbd8685c42571ad --incr --debug typical --relax --mt 2 -L xbip_utils_v3_0_10 -L c_reg_fd_v12_0_6 -L xbip_dsp48_wrapper_v3_0_4 -L xbip_pipe_v3_0_6 -L xbip_dsp48_addsub_v3_0_6 -L xbip_addsub_v3_0_6 -L c_addsub_v12_0_13 -L xil_defaultlib -L xbip_bram18k_v3_0_6 -L mult_gen_v12_0_15 -L axi_utils_v2_0_6 -L xbip_dsp48_multadd_v3_0_6 -L floating_point_v7_1_8 -L c_mux_bit_v12_0_6 -L c_shift_ram_v12_0_13 -L cmpy_v6_0_17 -L floating_point_v7_0_16 -L xfft_v9_1_2 -L dds_compiler_v6_0_18 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot fft_testbench_behav xil_defaultlib.fft_testbench xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 46b40167271d49a78bbd8685c42571ad --incr --debug typical --relax --mt 2 -L xbip_utils_v3_0_10 -L c_reg_fd_v12_0_6 -L xbip_dsp48_wrapper_v3_0_4 -L xbip_pipe_v3_0_6 -L xbip_dsp48_addsub_v3_0_6 -L xbip_addsub_v3_0_6 -L c_addsub_v12_0_13 -L xil_defaultlib -L xbip_bram18k_v3_0_6 -L mult_gen_v12_0_15 -L axi_utils_v2_0_6 -L xbip_dsp48_multadd_v3_0_6 -L floating_point_v7_1_8 -L c_mux_bit_v12_0_6 -L c_shift_ram_v12_0_13 -L cmpy_v6_0_17 -L floating_point_v7_0_16 -L xfft_v9_1_2 -L dds_compiler_v6_0_18 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot fft_testbench_behav xil_defaultlib.fft_testbench xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
