@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Apr 22 11:31:44 +0800 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim fft_testbench_behav -key {Behavioral:sim_1:Functional:fft_testbench} -tclbatch fft_testbench.tcl -view D:/BaiduNetdiskDownload/fft_test3/fft_test3/fft_testbench_behav.wcfg -view D:/BaiduNetdiskDownload/fft_test3/fft_test3/fft_float_tb_behav.wcfg -log simulate.log"
call xsim  fft_testbench_behav -key {Behavioral:sim_1:Functional:fft_testbench} -tclbatch fft_testbench.tcl -view D:/BaiduNetdiskDownload/fft_test3/fft_test3/fft_testbench_behav.wcfg -view D:/BaiduNetdiskDownload/fft_test3/fft_test3/fft_float_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
