# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/dell/Desktop/CameraLink/fft_test2/fft_test2.srcs/sources_1/ip/float2fix/float2fix.xci
# IP: The module: 'float2fix' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/CameraLink/fft_test2/fft_test2.srcs/sources_1/ip/float2fix/float2fix_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float2fix'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/dell/Desktop/CameraLink/fft_test2/fft_test2.srcs/sources_1/ip/float2fix/float2fix.xci
# IP: The module: 'float2fix' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/CameraLink/fft_test2/fft_test2.srcs/sources_1/ip/float2fix/float2fix_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float2fix'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
