# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/dell/Desktop/CameraLink/fft_test2/fft_test2.srcs/sources_1/ip/add32bits/add32bits.xci
# IP: The module: 'add32bits' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/CameraLink/fft_test2/fft_test2.srcs/sources_1/ip/add32bits/add32bits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add32bits'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/dell/Desktop/CameraLink/fft_test2/fft_test2.srcs/sources_1/ip/add32bits/add32bits.xci
# IP: The module: 'add32bits' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/CameraLink/fft_test2/fft_test2.srcs/sources_1/ip/add32bits/add32bits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add32bits'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
